

"agregar el responsive y css en el deploy"

"agregar el skeleton como tiene sacci"


"REVISAR SI ES EN EL ONSUBMIT DEL WALLET CUANDO ME CONFIRMA QUE UN PAGO SE REALIZO, XQ SI ES ASI, AHI DEBERIAMOS CREAR TODA LA INFO PARA GUARDARLA EN UN DOC"